language: python

python:

  - "3.5"
  - "3.6"

services:
  - postgresql

env:
  -DJANGO=2.2.5 DB=postgresql

install:
  - pip install -r requirements.txt
  - nvm install 11
  - npm install
  - npm run build

before_script:
  - cp .env.example .env
  - psql -c 'create database test_db;' -U postgres
  - python manage.py migrate

script:
  - python manage.py test
